name: 'Terraform Deploy'

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Setup Azure CLI
        uses: azure/setup-azure-cli@v1
        with:
          azure_cli_version: 'latest'

      - name: Azure Login
        run: |
          az cloud set --name AzureCloud
          az login --identity --client-id ${{ secrets.AZURE_CLIENT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
