name: 'Terraform Deploy'

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y curl lsb-release apt-transport-https
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Login with Azure CLI using User Assigned Managed Identity
        run: |
          az cloud set --name AzureCloud
          az login --identity --client-id ${{ secrets.AZURE_CLIENT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
