name: 'Terraform Deploy'

on:
  push:
    branches:
      - master
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          environment: azurecloud
          enable-AzPSSession: false
          allow-no-subscriptions: false
          audience: api://AzureADTokenExchange
        env:
          TERRAFORM_CLI_PATH: /home/runner/work/_temp/8dcb0d83-f6d4-40cf-85db-aecce8e08b3c
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
